# Generated by Django 5.1.2 on 2025-01-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='case',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='case',
            name='client',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='case',
        ),
        migrations.DeleteModel(
            name='CaseCategory',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
