# Generated by Django 5.1.2 on 2025-01-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_user_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.casecategory'),
        ),
    ]
