# Generated by Django 5.1.2 on 2025-01-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
