# Generated by Django 5.1.2 on 2025-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='c_image',
            field=models.FileField(default=1000, upload_to=''),
            preserve_default=False,
        ),
    ]
