# Generated by Django 5.1.2 on 2025-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agent_address_agent_is_active_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default=1000, max_length=200),
            preserve_default=False,
        ),
    ]
