# Generated by Django 5.1.2 on 2025-01-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_alter_casecategory_c_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='c_image',
            field=models.FileField(default='categories/default.jpg', upload_to='categories/'),
        ),
    ]
