# Generated by Django 5.1.2 on 2025-01-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
    ]
