# Generated by Django 5.1.2 on 2025-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_casecategory_c_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='c_name',
            field=models.CharField(max_length=100),
        ),
    ]
