# Generated by Django 5.1.2 on 2025-01-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_alter_casecategory_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
