# Generated by Django 5.1.2 on 2025-01-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_chatmessage_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
