# Generated by Django 5.1.2 on 2025-01-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_remove_chat_receiver_alter_chat_case_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
